/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package minicxiv;

import DAO.FornecedorDAO;
import TO.MovimentoTO;
import TO.ItemTO;
import DAO.ItemDAO;
import DAO.MovimentacaoDAO;
import DAO.ParametroDAO;
import static DAO.ParametroDAO.buscaProxVenda;
import static DAO.ParametroDAO.veEstoqueConsulta;
import DAO.TurmaDAO;
import TO.CaixaAuxTO;
import TO.FornecedorTO;
import TO.ParametroTO;
import TO.RelEntradaTO;
import TO.TurmaTO;
import appcontrolealuno.AlunoMain;
import appcontrolealuno.TurmaMain;
import db.DaoException;
import exceptions.ValidacaoException;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author desenv01
 */
public class LancaTurmaMain extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -2809442742901146299L;

    ParametroTO parametroGeral;

    static void setDadosItem(String codigoSelecionado, String descricaoSelecionada, String saldo) {
        if (codigoSelecionado.equals("")) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jTxtCodigo.setBackground(new Color(255, 0, 102));
                    jTxtCodigo.requestFocus();
                }
            });
        } else {
            jTxtCodigo.setText(codigoSelecionado);
            jTxtDescricao.setText(geral.Geral.CortaString(descricaoSelecionada, 30));
            jTxtSaldo.setText(saldo);
            jTxtQtd.requestFocus();
            jTxtQtd.setBackground(new Color(255, 0, 102));
        }
    }

    static void setDadosFornecedor(int codigoFornecedorSelecionado, String razaoFornecedorSelecionado) {
        if (codigoFornecedorSelecionado != 0) {
            jTxtCodigoTurma.setText(String.valueOf(codigoFornecedorSelecionado));
            jTxtSerie.setText(razaoFornecedorSelecionado);
        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtCodigo.setBackground(new Color(255, 0, 102));
                jTxtCodigo.requestFocus();
            }
        });
    }

    String titulo = "";
    NumberFormat duasDecimais = new DecimalFormat("########0.00", new DecimalFormatSymbols(Locale.ENGLISH));
    int item = 1;

    // Pega a data de hoje
    SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
    Date dataHoje = new Date(System.currentTimeMillis());
    String dataHojeS = formatarDate.format(dataHoje);

    private DefaultTableModel getTableModel() {
        return (DefaultTableModel) jTableMovCx.getModel();
    }

    /**
     * Creates new form AppGProtEl
     */
    public LancaTurmaMain() {
        try {
            parametroGeral = ParametroDAO.detalharParametro();
            initComponents();
            getTableModel().setRowCount(0);
            jTableMovCx.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
            jTableMovCx.setRowHeight(25);
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jTxtCodigo.setBackground(new Color(255, 0, 102));
                    jTxtCodigo.requestFocus();
                }
            });
        } catch (DaoException | SQLException ex) {
            Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro Acesso ao Banco de Dados.");
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMovCx = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTxtSaldo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButtonDinheiro = new javax.swing.JButton();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtAlunos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonDinheiro1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtDescricao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtCodigoTurma = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTxtSerie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("008");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("008");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jTableMovCx.setAutoCreateRowSorter(true);
        jTableMovCx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableMovCx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                " Código", "Nome", "Sexo", "Data Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMovCx.setShowHorizontalLines(false);
        jTableMovCx.setShowVerticalLines(false);
        jTableMovCx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMovCxMouseClicked(evt);
            }
        });
        jTableMovCx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableMovCxKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMovCx);
        if (jTableMovCx.getColumnModel().getColumnCount() > 0) {
            jTableMovCx.getColumnModel().getColumn(0).setMinWidth(65);
            jTableMovCx.getColumnModel().getColumn(0).setPreferredWidth(65);
            jTableMovCx.getColumnModel().getColumn(0).setMaxWidth(65);
            jTableMovCx.getColumnModel().getColumn(2).setMinWidth(80);
            jTableMovCx.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableMovCx.getColumnModel().getColumn(2).setMaxWidth(80);
            jTableMovCx.getColumnModel().getColumn(3).setMinWidth(100);
            jTableMovCx.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableMovCx.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lança Turma");

        jTxtSaldo.setEditable(false);
        jTxtSaldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSaldoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButtonDinheiro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDinheiro.setText("Confirma turma");
        jButtonDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDinheiroActionPerformed(evt);
            }
        });
        jButtonDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDinheiroKeyPressed(evt);
            }
        });

        jTxtCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCodigoFocusGained(evt);
            }
        });
        jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nome:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Código:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Alunos:");

        jTxtAlunos.setEditable(false);
        jTxtAlunos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTxtAlunos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDinheiro1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonDinheiro1.setText("Confirma aluno");
        jButtonDinheiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDinheiro1ActionPerformed(evt);
            }
        });
        jButtonDinheiro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDinheiro1KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Sexo:");

        jTxtDescricao.setEditable(false);
        jTxtDescricao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDescricaoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText(" Turma:");

        jTxtCodigoTurma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtCodigoTurma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCodigoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoTurmaActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxtSerie.setEditable(false);
        jTxtSerie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtSerie.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Série:");

        jDesktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtSaldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButtonDinheiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtAlunos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButtonDinheiro1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtDescricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtCodigoTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(561, 561, 561))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addComponent(jTxtCodigoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButtonDinheiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtDescricao)
                            .addComponent(jTxtSerie))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(jButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(48, 48, 48)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDinheiro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaProximaVenda() throws HeadlessException {
        // Busca proxima venda
        try {
            jTxtAlunos.setText(String.valueOf(buscaProxVenda()));
            ParametroDAO.gravaProximaVenda();
        } catch (DaoException | SQLException ex) {
            Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro Acesso ao Banco de Dados.");
        }
    }


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TurmaMain frm = new TurmaMain();
        getDesktopPane().add(frm);
        int x = (getDesktopPane().getWidth() / 2) - (frm.getWidth() / 2);
        int y = (getDesktopPane().getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y);
        frm.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtCodigoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoTurmaActionPerformed
        if (!jTxtCodigoTurma.getText().equals("")) {
            // localiza turma pelo codigo
            TurmaTO turma = new TurmaTO();
            try {
                turma = TurmaDAO.detalharTurma(Integer.valueOf(jTxtCodigoTurma.getText()));
            } catch (DaoException ex) {
                Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro consulta BD!");
                jTxtCodigoTurma.requestFocus();
            }
            if (turma == null) {
                JOptionPane.showMessageDialog(this, "Turma " + jTxtCodigoTurma.getText() + " \nNão cadastrada!");
                jTxtCodigoTurma.requestFocus();
            } else {
                jTxtSerie.setText(turma.getSerie());
            }
        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtCodigo.setBackground(new Color(255, 0, 102));
                jTxtCodigo.requestFocus();
            }
        });
    }//GEN-LAST:event_jTxtCodigoTurmaActionPerformed

    private void jTxtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDescricaoActionPerformed

    private void jButtonDinheiro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDinheiro1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDinheiro1KeyPressed

    private void jButtonDinheiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDinheiro1ActionPerformed
        jTxtQtdActionPerformed(null);
    }//GEN-LAST:event_jButtonDinheiro1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AlunoMain alun = new AlunoMain();
        jDesktopPane.add(alun);
        int x = (jDesktopPane.getWidth() / 2) - (alun.getWidth() / 2);
        int y = (jDesktopPane.getHeight() / 2) - (alun.getHeight() / 2);
        alun.setLocation(x, y);
        alun.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigoFocusGained
        jTxtCodigo.setBackground(new Color(255, 0, 102));
        jTxtQtd.setBackground(jTxtSaldo.getBackground());
    }//GEN-LAST:event_jTxtCodigoFocusGained

    private void jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoActionPerformed
        // Busca item e coloca descricao e pula para quantidade:

        try {
            CaixaAuxTO dataCaixa = ParametroDAO.buscaDataCaixa();
            jTxtDataVenda.setText(dataCaixa.getDataCx());
        } catch (DaoException | SQLException ex) {
            Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro Acesso ao Banco de Dados");
        }

        ItemTO it = new ItemTO();
        // Alinhas colunas a direita
        DefaultTableCellRenderer alignDireita = new DefaultTableCellRenderer();
        alignDireita.setHorizontalAlignment(JLabel.RIGHT);
        TableColumn co04 = jTableMovCx.getColumnModel().getColumn(4);
        co04.setCellRenderer(alignDireita);
        TableColumn co03 = jTableMovCx.getColumnModel().getColumn(3);
        co03.setCellRenderer(alignDireita);
        TableColumn co02 = jTableMovCx.getColumnModel().getColumn(2);
        co02.setCellRenderer(alignDireita);

        DefaultTableCellRenderer alignCentro = new DefaultTableCellRenderer();
        alignCentro.setHorizontalAlignment(JLabel.CENTER);
        TableColumn co00 = jTableMovCx.getColumnModel().getColumn(0);
        co00.setCellRenderer(alignCentro);

        try {
            if (jTxtCodigo.getText().toUpperCase().substring(0, 1).equals("R")) {
                it = ItemDAO.detalharItemReferencia(jTxtCodigo.getText().substring(1, jTxtCodigo.getText().length()));
            } else {
                if (jTxtCodigo.getText().length() > 5) {
                    if (jTxtCodigo.getText().substring(0, 1).equals("2") & parametroGeral.getEtiquetaComidaKg().equals("S")) {
                        it = ItemDAO.detalharItemETQ(jTxtCodigo.getText());
                    } else {
                        it = ItemDAO.detalharItemEAN(jTxtCodigo.getText());
                    }
                } else {
                    it = ItemDAO.detalharItem(jTxtCodigo.getText());
                }
            }
        } catch (DaoException | SQLException ex) {
            Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro na aplicacao");
            //
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jTxtCodigo.setBackground(new Color(255, 0, 102));
                    jTxtCodigo.requestFocus();
                }
            });
        }
        if (it == null) {
            JOptionPane.showMessageDialog(this, "Codigo inválido!");
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jTxtCodigo.setBackground(new Color(255, 0, 102));
                    jTxtCodigo.requestFocus();
                }
            });
        } else {
            jTxtCodigo.setText(it.getCodigo());
            jTxtDescricao.setText(geral.Geral.CortaString(it.getDescricao(), 30));
            jTxtSaldo.setText(duasDecimais.format(it.getEstoque()));
        }
        jTxtCodigo.setBackground(new Color(255, 0, 102));
        jTxtQtd.requestFocus();
    }//GEN-LAST:event_jTxtCodigoActionPerformed

    private void jButtonDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDinheiroKeyPressed
        inicioFechamentoEntrada();
    }//GEN-LAST:event_jButtonDinheiroKeyPressed

    private void jButtonDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDinheiroActionPerformed

        inicioFechamentoEntrada();
    }//GEN-LAST:event_jButtonDinheiroActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSaldoActionPerformed

    private void jTableMovCxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableMovCxKeyPressed
        Double total = Double.valueOf(jTxtTotalGeral.getText());
        Double excluido = Double.valueOf(jTableMovCx.getValueAt(jTableMovCx.getSelectedRow(), 4).toString());
        jTxtTotalGeral.setText(String.valueOf(duasDecimais.format(total - excluido)));
        getTableModel().removeRow(jTableMovCx.getSelectedRow());
        jTxtNumItens.setText(String.valueOf(Integer.parseInt(jTxtNumItens.getText()) - 1));
        if (Integer.parseInt(jTxtNumItens.getText()) <= 1) {
            jLabelItem.setText("Item");
        }
    }//GEN-LAST:event_jTableMovCxKeyPressed

    private void jTableMovCxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMovCxMouseClicked
        Double total = Double.valueOf(jTxtTotalGeral.getText());
        Double excluido = Double.valueOf(jTableMovCx.getValueAt(jTableMovCx.getSelectedRow(), 4).toString());
        jTxtTotalGeral.setText(String.valueOf(duasDecimais.format(total - excluido)));
        getTableModel().removeRow(jTableMovCx.getSelectedRow());
        jTxtNumItens.setText(String.valueOf(Integer.parseInt(jTxtNumItens.getText()) - 1));
        if (Integer.parseInt(jTxtNumItens.getText()) <= 1) {
            jLabelItem.setText("Item");
        }
    }//GEN-LAST:event_jTableMovCxMouseClicked


    private void inicioFechamentoEntrada() throws NumberFormatException, HeadlessException {
        // Pede confirmação para emissao do relatório
        Object[] options = {"Sim", "Não"};
        int q = JOptionPane.showOptionDialog(null,
                "Confirma entrada ?", "Saída",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[1]);
        if (q == JOptionPane.YES_OPTION) {

            // Venda = 0
            if (jTxtTotalGeral.getText().equals("0.00")) {
                JOptionPane.showMessageDialog(this, "Entrada sem Item!");
                return;
            }
            // Monta array objetos para gravar
            // Declarar Movimento TO
            int codigoFornecedor;
            if (!jTxtSerie.getText().equals("")) {
                codigoFornecedor = Integer.valueOf(jTxtCodigoTurma.getText());
            } else {
                codigoFornecedor = 0;
            }

            ArrayList<MovimentoTO> m = new ArrayList<>();
            for (int i = 0; i < Integer.parseInt(jTxtNumItens.getText()); i++) {
                MovimentoTO to = new MovimentoTO();
                to.setNdoc(Integer.parseInt(jTxtAlunos.getText()));
                to.setSequencia(i + 1);
                to.setCodigo(jTableMovCx.getValueAt(i, 0).toString());
                to.setTipoMov("E");
                to.setValorUnit(Double.parseDouble(jTableMovCx.getValueAt(i, 2).toString()));
                to.setQuant(Double.parseDouble(jTableMovCx.getValueAt(i, 3).toString().replace(",", ".")));
                to.setValorTotal(Double.parseDouble(jTableMovCx.getValueAt(i, 4).toString()));
                to.setDescricao(jTableMovCx.getValueAt(i, 1).toString());
                to.setDataMov(dataHojeS);
                to.setCodigoFornecedor(codigoFornecedor);
                m.add(to);
            }
            ArrayList<RelEntradaTO> relEntrada;
            try {
                //Grava dados no banco
                MovimentacaoDAO.inserirMovimentoEntrada(m);
                relEntrada = MovimentacaoDAO.transformaMovimentoTOemRelEntradaTO(m, "Entrada Manual.");
            } catch (DaoException | SQLException ex) {
                Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao gravar entrada");
                return;
            }
            if (relEntrada.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Iten(s) não encontrado(s)!");
                return;
            }
            // limpa campos da tela
            getTableModel().setRowCount(0);
            jTxtTotalGeral.setText("0.00");
            jTxtAlunos.setText("");
            jTxtNumItens.setText("");
            // Imprime tiket venda
            try {
                // Pergunta se imprime ou gera PDF
                Object[] options1 = {"Impressora", "Tela"};
                int q1 = JOptionPane.showOptionDialog(null,
                        "O relatório será?", "Saída",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                        options1, options1[1]);
                if (q1 == JOptionPane.YES_OPTION) {

                    // compilacao do JRXML
                    JasperReport report = JasperCompileManager.compileReport(geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.jrxml");
                    JasperPrint print = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(relEntrada));
                        // exportacao do relatorio para outro formato, no caso PDF 
                    //JasperExportManager.exportReportToPdfFile(print, geral.Geral.getDiretorioAtual() + "\\Relatorios\\RelatorioClientes.pdf");  
                    //JasperViewer.viewReport(print, false);
                    JasperPrintManager.printPage(print, 0, false);

                } else {
                    JasperReport report = JasperCompileManager.compileReport(geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.jrxml");
                    JasperPrint print = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(relEntrada));
                    // exportacao do relatorio para outro formato, no caso PDF 
                    JasperExportManager.exportReportToPdfFile(print, geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.pdf");
                    JasperViewer.viewReport(print, false);
                }
            } catch (JRException | ValidacaoException ex) {
                Logger.getLogger(LancaTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao imprimir entrada!");
            }
        }

    }


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonDinheiro;
    private javax.swing.JButton jButtonDinheiro1;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMovCx;
    private javax.swing.JTextField jTxtAlunos;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtCodigoTurma;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtSaldo;
    private javax.swing.JTextField jTxtSerie;
    // End of variables declaration//GEN-END:variables

}
